# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhraseiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'PhraseSDK'

  # Pods for PhraseiOS

  target 'PhraseiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhraseiOSUITests' do
    # Pods for testing
  end

end
